config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'explore', to: 'posts#browse', as: :browse_posts

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user

  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user


  get 'notifications', to: 'notifications#index'

  get 'notifications/:id/link_through', to:
  'notifications#link_through', as: :link_through

  get 'notifications/:id/follow_link_through', to:
  'notifications#follow_link_through', as: :follow_link_through

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  devise_for :users, controllers: { registrations: 'registrations' }


  get ':user_name', to: 'profiles#show', as: :profile

  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notified_by, class_name: 'User'

  belongs_to :user
  belongs_to :post

  validates :user_id, :notified_by_id, :post_id, :identifier, :notice_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.notifications.all.order('created_at DESC').page(params[:page]).per(10)
  end

  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to post_path @notification.post
  end

  def follow_link_through
    @notification = Notification.find(params[:id])
    notified_by = User.find(@notification.notified_by_id)
    @notification.update(read: true)
    redirect_to profile_path(notified_by.user_name)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<div class="thumb-img text-center">
  <%= post_user_avatar_select(notification.notified_by) %>
</div>
<li>
  <% if notification.notice_type == 'comment' %>
    <%= link_to "#{notification.notified_by.user_name} #{notification.notice_type}ed on your post", link_through_path(notification) %>
  <% elsif notification.notice_type == 'like' %>
    <%= link_to "#{notification.notified_by.user_name} #{notification.notice_type}d your post", link_through_path(notification) %>
  <% else %>
    <%= link_to "#{notification.notified_by.user_name} started #{notification.notice_type}ing you!", follow_link_through_path(notification)%>
  <% end %>

  &nbsp;&nbsp;&nbsp;&nbsp;

  <span class="notification-time-ago">
    ⟶
    &nbsp;
    <%= "#{time_ago_in_words(notification.created_at)}" %>
  </span>
</li>
<hr class="notif-margin">

app/views/notifications/_notification_dropdown.html.erb
<div class="dropdown notification-dropdown">
  <button class="btn btn-default dropdown-toggle navy-glyphicon nav-link" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    <% if current_user.notifications.where(read: false).count >= 1 %>
      <%= current_user.notifications.where(read: false).count %>
    <% end %>
    <span class="glyphicon glyphicon-flag"></span>
  </button>

  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li class="dropdown-header text-center" id="notification-title">
      Notifications
    </li><hr class="notif-margin">
      <%= render current_user.notifications.order('created_at DESC').last(5) %>
    <li class="text-center">
      <%= link_to 'View All', notifications_path %>
    </li>
  </ul>
</div>

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="notification-index-list">
        <% @notifications.each do |notification| %>
          <%= render 'notification', notification: notification %>
        <% end %>
      </ul>
      <div class="text-center">
        <%= paginate @notifications %>
      </div>
    </div>
  </div>
</div>