config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'explore', to: 'posts#browse', as: :browse_posts

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user

  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user


  get 'notifications', to: 'notifications#index'

  get 'notifications/:id/link_through', to:
  'notifications#link_through', as: :link_through

  get 'notifications/:id/follow_link_through', to:
  'notifications#follow_link_through', as: :follow_link_through

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  devise_for :users, controllers: { registrations: 'registrations' }


  get ':user_name', to: 'profiles#show', as: :profile

  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  paginates_per 2

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # Validations for posts
  validates :user_id, presence: true
  validates :image, attachment_presence: true
  validates :caption, length: { minimum: 3, maximum: 300 }, allow_blank: true

  has_attached_file :image, styles: { medium: "640x" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # Only show followed users and the current user in dashboard
  scope :of_followed_users, -> (following_users) { where user_id: following_users }
  scope :of_current_user, -> (current_user) { where user_id: current_user }

  scope :of_current_and_followed_users, -> (following, current) {         self.of_followed_users(following).or(self.of_current_user(current))
  }
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :like,
    :unlike]
  before_action :owned_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!


  def index
    @posts = Post.of_current_and_followed_users(current_user.following, current_user).order('created_at DESC').page(params[:page]) #.per(3)
  end

  def browse
    @posts = Post.all.order('created_at DESC').page(params[:page]) #.per(10)
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to posts_path
    else
      flash.now[:alert] = "Your new post couldn't be created!
      Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed. Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def like
    if @post.liked_by current_user
      create_notification @post
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unlike
    if @post.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end


  private

    def post_params
      params.require(:post).permit(:image, :caption)
    end

    def find_post
      @post = Post.find(params[:id])
    end

    def owned_post
      unless current_user == @post.user
        flash[:alert] = "That post doesn't belong to you!"
        redirect_to root_path
      end
    end

    def create_notification(post)
      return if post.user.id == current_user.id

      Notification.create(user_id: post.user.id,
      notified_by_id: current_user.id,
      post_id: post.id,
      identifier: post.id, #The user has liked this specific post
      notice_type: 'like')
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
    count_likers(votes)
  end

  def liked_post(post)
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end


private

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end
end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_image_select(@post) %>
        <%= simple_form_for @post, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4> Upload an image (this is required):</h4>
              <%= f.input :image, label: false, input_html: {
                onChange: 'loadFile(event)' } %>
            </div>

            <div class="form-group text-center">
              <%= f.text_field :caption, label: false, class: 'form-control' %>
            </div>

            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn btn-success' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_likes.html.erb
<div class="likes" id="likes_<%= post.id %>">
  <%= display_likes post %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img">
        <%= post_user_avatar_select(User.find(post.user)) %>
      </div>
      <div class="user-name">
        <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
      </div>
      <div class="time-ago">
        <%= time_ago_in_words post.created_at %>
      </div>
    </div>

    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>

    <div class="post-bottom">
      <%= render 'posts/likes', post: post %>
      <div class="caption">
        <div class="caption-content">
          <div class="user-name">
            <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
          </div>
          <%= post.caption %>
        </div>

        <div class="comments" id="comments_<%= post.id %>">
          <% if post.comments.any? %>
            <div class="paginator" id="#comments-paginator-<%= post.id %>">
              <% unless post.comments.count <= 4 %>
                <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"} %>
              <% end %>
            </div>
            <%= render post.comments.last(4), post: post %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <%# link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}", class: "like glyphicon #{liked_post post}" %>
        <% if current_user.liked?(post) %>
          <%= link_to '', unlike_post_path(post.id), remote: true,
          id: "like_#{post.id}", class: "like glyphicon #{liked_post post}" %>
        <% else %>
          <%= link_to '', like_post_path(post.id), remote: true,
          id: "like_#{post.id}", class: "like glyphicon #{liked_post post}" %>
        <% end %>
      </div>

      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment-content", id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_dashboard.html.erb
<div id="posts">
  <%= render 'posts' %>
</div>

<div id="paginator" class="text-center">
  <%= link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more') %>
</div>

app/views/posts/_post_dashboard.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/browse.html.erb
<%= provide(:title, 'Explore') %>
<%= render 'post_dashboard', posts: @posts %>

app/views/posts/edit.html.erb
<% provide(:title, 'Edit Post') %>
<div class="text-center">
  <%= render 'form' %>

  <div class="text-center edit-links">
    <%= link_to "Delete Post", post_path(@post), method: :delete,
    data: { confirm: "Are you sure you want to delete this post?" } %>
    |
    <%= link_to "Cancel", posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'posts/post_dashboard', posts: @posts %>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#like_<%= @post.id %>").attr("href", '/posts/<%= @post.id %>/unlike');
$("#likes_<%= @post.id %>").html("<%= escape_javascript(render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.erb
<% provide(:title, 'New Post') %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% provide(:title, 'Show') %>

<%= render 'post', post: @post %>
<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
  </div>
<% end %>

app/views/posts/unlike.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
$("#like_<%= @post.id %>").attr("href", '/posts/<%= @post.id %>/like');
$("#likes_<%= @post.id %>").html("<%= escape_javascript(render partial: 'posts/likes', locals: { post: @post} ) %>");