config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'explore', to: 'posts#browse', as: :browse_posts

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user

  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user


  get 'notifications', to: 'notifications#index'

  get 'notifications/:id/link_through', to:
  'notifications#link_through', as: :link_through

  get 'notifications/:id/follow_link_through', to:
  'notifications#follow_link_through', as: :follow_link_through

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  devise_for :users, controllers: { registrations: 'registrations' }


  get ':user_name', to: 'profiles#show', as: :profile

  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <span class="glyphicon glyphicon-camera navy-glyphicon"></span>
        <%= link_to "Snapshot", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= render 'notifications/notification_dropdown' %></li>
        <li><%= link_to "New Post", new_post_path %></li>
        <li><%= link_to "Explore", browse_posts_path %></li>
        <li><%= link_to 'Profile', profile_path(current_user.user_name) %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: [:alert, alert_for(message_type)] %>
      <% end %>
      <%= yield %>
  </body>
</html>